version: "3"
services:
  mongo:
    image: mongo:5.0
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ignite_mongo_data:/data/db
  web:
    build: "."
    ports:
      - "4000:4000"
    env_file:
      - .env
volumes:
  ignite_mongo_data:
