name: Validate PR (Desktop)
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/desktop/**"
      - "package.json"
      - ".github/workflows/validate-pr-desktop.yml"

jobs:
  validate-pr-desktop:
    name: Validate PR (Desktop)
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn typecheck --scope=desktop

      - name: Lint
        run: yarn lint --scope=desktop
